
-- Generated by ORDS REST Data Services 18.3.0.r2701456
-- Schema: APEX_ANALYTICS  Date: Wed Dec 26 08:38:10 2018 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'APEX Analytics Endpoint',
      p_base_path      => '/data/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'APEX Analytics Endpoint',
      p_pattern        => 'collect',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'APEX Analytics Endpoint',
      p_pattern        => 'collect',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'BEGIN
  apexanalytics_app_pkg.process_rest_post_call(p_json_clob => :body_text,
                                               p_app_id    => 280);
END;');

        
COMMIT;

END;